using System.Text;
using AnalyticsReporting.Core;
using AnalyticsReporting.Infrastructure;
namespace AnalyticsReporting.Tests;

[TestClass]
public sealed class StreamingAndResumeTests
{
    [TestMethod] public async Task Five_mebibyte_upload_uses_bounded_64_kibibyte_reads() { var root = Path.Combine(Path.GetTempPath(), $"analytics-{Guid.NewGuid():N}"); try { var source = new TrackingStream(5 * 1024 * 1024); var store = new LocalFileStore(root); await store.SaveAsync(Guid.NewGuid(), source, default); Assert.IsLessThanOrEqualTo(65536, source.LargestRead); Assert.AreEqual(5 * 1024 * 1024, source.BytesRead); } finally { if (Directory.Exists(root)) Directory.Delete(root, true); } }
    [TestMethod] public async Task Interrupted_worker_resumes_from_checkpoint_without_duplicate_rows() { var csv = string.Join('\n', Enumerable.Range(1, 1200).Select(i => $"category-{i % 4},{i}.00")); var files = new MemoryFiles(csv); var store = new MemoryJobs(); var job = new ImportJob(Guid.NewGuid(), "input.csv", "key", Encoding.UTF8.GetByteCount(csv), DateTimeOffset.UtcNow); store.Job = job; store.CancelAfterFirstCheckpoint = true; var processor = new CsvJobProcessor(files, store); await Assert.ThrowsExactlyAsync<OperationCanceledException>(() => processor.ProcessAsync(job, default)); Assert.AreEqual(500, job.ProcessedLines); store.CancelAfterFirstCheckpoint = false; await processor.ProcessAsync(job, default); Assert.AreEqual(JobStatus.Completed, job.Status); Assert.AreEqual(1200, job.ProcessedLines); Assert.HasCount(1200, store.Records); }
    private sealed class TrackingStream : Stream { private int remaining; private readonly int length; public TrackingStream(int length) { this.length = length; remaining = length; } public int LargestRead; public int BytesRead; public override async ValueTask<int> ReadAsync(Memory<byte> buffer, CancellationToken ct = default) { LargestRead = Math.Max(LargestRead, buffer.Length); var count = Math.Min(buffer.Length, remaining); remaining -= count; BytesRead += count; await Task.Yield(); return count; } public override bool CanRead => true; public override bool CanSeek => false; public override bool CanWrite => false; public override long Length => length; public override long Position { get => BytesRead; set => throw new NotSupportedException(); } public override void Flush() { } public override int Read(byte[] b, int o, int c) => throw new NotSupportedException(); public override long Seek(long o, SeekOrigin so) => throw new NotSupportedException(); public override void SetLength(long v) => throw new NotSupportedException(); public override void Write(byte[] b, int o, int c) => throw new NotSupportedException(); }
    private sealed class MemoryFiles(string csv) : IFileStore { public Task<string> SaveAsync(Guid id, Stream s, CancellationToken ct) => Task.FromResult("key"); public Task<Stream> OpenReadAsync(string key, CancellationToken ct) => Task.FromResult<Stream>(new MemoryStream(Encoding.UTF8.GetBytes(csv))); }
    private sealed class MemoryJobs : IJobStore { public ImportJob Job = null!; public bool CancelAfterFirstCheckpoint; public Dictionary<long, OperationalRecord> Records = []; public Task AddAsync(ImportJob j, CancellationToken ct) { Job = j; return Task.CompletedTask; } public Task<ImportJob?> FindAsync(Guid id, CancellationToken ct) => Task.FromResult<ImportJob?>(Job); public Task<ImportJob?> LeaseNextAsync(CancellationToken ct) => Task.FromResult<ImportJob?>(Job); public Task SaveAsync(ImportJob j, CancellationToken ct) { if (CancelAfterFirstCheckpoint && j.ProcessedLines == 500) throw new OperationCanceledException(); return Task.CompletedTask; } public Task AddRecordsAsync(IReadOnlyCollection<OperationalRecord> rows, CancellationToken ct) { foreach (var row in rows) Records.TryAdd(row.LineNumber, row); return Task.CompletedTask; } public Task<IReadOnlyList<(string Category, decimal Total)>> ReportAsync(CancellationToken ct) => Task.FromResult<IReadOnlyList<(string, decimal)>>([]); }
}
