using System.Globalization;
namespace AnalyticsReporting.Core;

public enum JobStatus { Queued, Processing, Completed, Failed }
public sealed class ImportJob { private ImportJob() { } public ImportJob(Guid id, string fileName, string storageKey, long size, DateTimeOffset now) { Id = id; FileName = fileName; StorageKey = storageKey; Size = size; Status = JobStatus.Queued; CreatedAt = now; } public Guid Id { get; private set; } public string FileName { get; private set; } = string.Empty; public string StorageKey { get; private set; } = string.Empty; public long Size { get; private set; } public JobStatus Status { get; private set; } public long ProcessedLines { get; private set; } public DateTimeOffset CreatedAt { get; private set; } public string? Error { get; private set; } public long Version { get; private set; } public void Start() { if (Status is not (JobStatus.Queued or JobStatus.Processing)) throw new InvalidOperationException(); Status = JobStatus.Processing; Version++; } public void Checkpoint(long lines) { if (Status != JobStatus.Processing || lines < ProcessedLines) throw new InvalidOperationException(); ProcessedLines = lines; Version++; } public void Complete() { Status = JobStatus.Completed; Version++; } public void Fail(string error) { Status = JobStatus.Failed; Error = error; Version++; } }
public sealed record OperationalRecord(Guid Id, Guid JobId, long LineNumber, string Category, decimal Amount);
public sealed record JobDto(Guid Id, string FileName, long Size, JobStatus Status, long ProcessedLines, string? Error);
public interface IFileStore { Task<string> SaveAsync(Guid jobId, Stream source, CancellationToken ct); Task<Stream> OpenReadAsync(string key, CancellationToken ct); }
public interface IJobStore { Task AddAsync(ImportJob job, CancellationToken ct); Task<ImportJob?> FindAsync(Guid id, CancellationToken ct); Task<ImportJob?> LeaseNextAsync(CancellationToken ct); Task SaveAsync(ImportJob job, CancellationToken ct); Task AddRecordsAsync(IReadOnlyCollection<OperationalRecord> records, CancellationToken ct); Task<IReadOnlyList<(string Category, decimal Total)>> ReportAsync(CancellationToken ct); }
public sealed class ImportService(IFileStore files, IJobStore jobs, TimeProvider clock)
{ public async Task<JobDto> UploadAsync(string fileName, long size, Stream source, CancellationToken ct) { if (size <= 0) throw new ArgumentException("File is empty."); var id = Guid.NewGuid(); var key = await files.SaveAsync(id, source, ct); var job = new ImportJob(id, Path.GetFileName(fileName), key, size, clock.GetUtcNow()); await jobs.AddAsync(job, ct); return Map(job); } public async Task<JobDto> GetAsync(Guid id, CancellationToken ct) => Map(await jobs.FindAsync(id, ct) ?? throw new KeyNotFoundException()); private static JobDto Map(ImportJob j) => new(j.Id, j.FileName, j.Size, j.Status, j.ProcessedLines, j.Error); }
public sealed class CsvJobProcessor(IFileStore files, IJobStore jobs)
{ public async Task ProcessAsync(ImportJob job, CancellationToken ct) { job.Start(); await jobs.SaveAsync(job, ct); await using var stream = await files.OpenReadAsync(job.StorageKey, ct); using var reader = new StreamReader(stream, bufferSize: 65536, leaveOpen: false); long line = 0; while (line < job.ProcessedLines && await reader.ReadLineAsync(ct) is not null) line++; var batch = new List<OperationalRecord>(500); while (await reader.ReadLineAsync(ct) is string text) { line++; var parts = text.Split(','); if (parts.Length != 2 || !decimal.TryParse(parts[1], NumberStyles.Number, CultureInfo.InvariantCulture, out var amount)) throw new InvalidDataException($"Invalid CSV at line {line}."); batch.Add(new(Guid.NewGuid(), job.Id, line, parts[0].Trim(), amount)); if (batch.Count == 500) { await jobs.AddRecordsAsync(batch, ct); job.Checkpoint(line); await jobs.SaveAsync(job, ct); batch.Clear(); } } if (batch.Count > 0) { await jobs.AddRecordsAsync(batch, ct); job.Checkpoint(line); await jobs.SaveAsync(job, ct); } job.Complete(); await jobs.SaveAsync(job, ct); } }
