namespace ReconciliationPlatform.Core;

public sealed record MismatchEvent(Guid MessageId, string SourceSystem, string RecordKey, decimal ExpectedAmount, decimal ActualAmount, string CorrelationId, DateTimeOffset OccurredAt);
public sealed class InboxMessage { private InboxMessage() { } public InboxMessage(MismatchEvent e, string payload) { MessageId = e.MessageId; SourceSystem = e.SourceSystem; RecordKey = e.RecordKey; CorrelationId = e.CorrelationId; Payload = payload; ReceivedAt = DateTimeOffset.UtcNow; } public Guid MessageId { get; private set; } public string SourceSystem { get; private set; } = string.Empty; public string RecordKey { get; private set; } = string.Empty; public string CorrelationId { get; private set; } = string.Empty; public string Payload { get; private set; } = string.Empty; public DateTimeOffset ReceivedAt { get; private set; } public DateTimeOffset? ProcessedAt { get; private set; } public void MarkProcessed(DateTimeOffset now) => ProcessedAt = now; }
public sealed class ExceptionCase { private ExceptionCase() { } public ExceptionCase(Guid id, string source, string key, decimal expected, decimal actual, string correlation, DateTimeOffset now) { Id = id; SourceSystem = source; RecordKey = key; ExpectedAmount = expected; ActualAmount = actual; CorrelationId = correlation; CreatedAt = now; } public Guid Id { get; private set; } public string SourceSystem { get; private set; } = string.Empty; public string RecordKey { get; private set; } = string.Empty; public decimal ExpectedAmount { get; private set; } public decimal ActualAmount { get; private set; } public string CorrelationId { get; private set; } = string.Empty; public DateTimeOffset CreatedAt { get; private set; } }
public sealed class NotificationMessage { private NotificationMessage() { } public NotificationMessage(Guid id, Guid caseId, string correlation, DateTimeOffset now) { Id = id; CaseId = caseId; CorrelationId = correlation; CreatedAt = now; NextAttemptAt = now; } public Guid Id { get; private set; } public Guid CaseId { get; private set; } public string CorrelationId { get; private set; } = string.Empty; public DateTimeOffset CreatedAt { get; private set; } public DateTimeOffset NextAttemptAt { get; private set; } public int Attempts { get; private set; } public DateTimeOffset? SentAt { get; private set; } public string? LastError { get; private set; } public void Sent(DateTimeOffset now) => SentAt = now; public void Failed(string error, DateTimeOffset now) { Attempts++; LastError = error; NextAttemptAt = now.AddSeconds(Math.Pow(2, Attempts)); } }
public sealed record DeadLetter(Guid Id, Guid MessageId, string CorrelationId, string Error, string Payload, DateTimeOffset DeadLetteredAt);
public interface IReconciliationStore { Task<bool> AcceptAsync(MismatchEvent e, CancellationToken ct); Task<MismatchEvent?> NextAsync(CancellationToken ct); Task<bool> CreateExceptionOnceAsync(MismatchEvent e, CancellationToken ct); Task<NotificationMessage?> NextNotificationAsync(DateTimeOffset now, CancellationToken ct); Task MarkNotificationSentAsync(NotificationMessage message, DateTimeOffset now, CancellationToken ct); Task RetryOrDeadLetterAsync(NotificationMessage message, string error, DateTimeOffset now, int maxAttempts, CancellationToken ct); Task<IReadOnlyList<DeadLetter>> DeadLettersAsync(CancellationToken ct); }
public interface INotificationGateway { Task SendAsync(Guid caseId, string correlationId, CancellationToken ct); }
public sealed class IngestionService(IReconciliationStore store) { public Task<bool> IngestAsync(MismatchEvent e, CancellationToken ct) => store.AcceptAsync(e, ct); }
public sealed class ReconciliationService(IReconciliationStore store) { public async Task<bool> ProcessNextAsync(CancellationToken ct) { var e = await store.NextAsync(ct); return e is not null && await store.CreateExceptionOnceAsync(e, ct); } }
public sealed class NotificationService(IReconciliationStore store, INotificationGateway gateway, TimeProvider clock)
{ public async Task<bool> ProcessNextAsync(CancellationToken ct) { var message = await store.NextNotificationAsync(clock.GetUtcNow(), ct); if (message is null) return false; try { await gateway.SendAsync(message.CaseId, message.CorrelationId, ct); await store.MarkNotificationSentAsync(message, clock.GetUtcNow(), ct); } catch (Exception e) when (e is not OperationCanceledException) { await store.RetryOrDeadLetterAsync(message, e.Message, clock.GetUtcNow(), 3, ct); } return true; } }
